### ISSUE TITLE
EXAMPLE RDS: Schuhplattlerabend (Cultural Event)

### ISSUE THREAD

**Issue by eliaskaerle** [ODTA/ds#1]
Umut & Elias

## What is the topic that should be discussed?
With this RDS we want to propose a DS for the cultural event type Schuhplattlerabend.

## Why is this topic important for a broader audience?
Schuhplattlerabend is a topic of general touristic interest and should be given more attention, especially in German-speaking regions of Europe. Therefore we propose an explicit DS for this kind of cultural event.

## (Optional) How can/cannot this issue be represented in schema.org?
Schuhplattlerabend can be represented almost purely in schema.org, just the base class, odta:Schuplattlerabend, and range of the schema:performer property (odta:Schuhplattlergruppe, sub class of odta:Brauchtumgsgruppe, sibling of odta:Krampusgruppe) need to be extended (see next section).

## (Optional) How should schema.org be extended if necessary?
To represent the Schuhplattlerabend as a ds we require new classes:
* odta:Schuplattlerabend
* odta:Brauchtumgsgruppe
* odta:Schuhplattlergruppe
* odta:Krampusgruppe

**Comment by sumutcan** [comment]
are these also relevant for south tyrol? do they have the same name?

**Comment by eliaskaerle** [comment]
They do, yes.

Not sure about the odta:Brauchtumsgruppe though. Do you think we should keep this class name even more generic?

**Comment by sumutcan** [comment]
I would recommend we go first for the subtypes that are relevant the largest possible portion of ODTA. The others can be also implemented in individual systems or discussed later.

**Comment by eliaskaerle** [comment]
agreed!

**Comment by sumutcan** [comment]
what would be the english translation for these types?

**Comment by asolvo** [comment]
I would suggest following the common naming conventions, e.g. using English terms for the names of the classes. 
You should use: 

- odta:SchuhplattlerEvening
- odta:CustomsGroup
- odta:SchuhplattlerGroup
- odta:KrampusGroup

**Comment by BjoernWF** [comment]
@eliaskaerle Krabben pulen

**Comment by asolvo** [comment]
When do you start with the 13 issues regarding all suggested domain specifications?

**Comment by eliaskaerle** [comment]
Since this issue was only made for demonstration purposes, I gonna close it now.
