### ISSUE TITLE
[RC] LodgingBusiness

### ISSUE THREAD

**Issue by eliaskaerle** [ODTA/ds#11]
This is the RC (Request for Comments) for the LodgingBusiness RDS. Please use the comments section below for discussions.

RDS Abstract:
In this RDS we propose a Domain Specification (DS) for lodging businesses, based on schema.org/LodgingBusiness, as used in the GNTB’s “Knowledge Graph für den Deutschlandtourismus” project. The DS holds all properties required to annotate a lodging business sufficiently using just the vocabulary of schema.org. However, to annotate the type of license applied to the data set we suggest modifying the original schema.org vocabulary.

Link to RC: https://github.com/ODTA/ds/blob/main/docs/rc/LodgingBusinessDS-RC-RDS.pdf
Link to RC's DS representation: https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=1ygSIMu-J

**Comment by FallicoNRW** [comment]
2.6 contactPoint - what does contact point mean in this context?

**Comment by FallicoNRW** [comment]
2.24 photo - is there a specific reason for calling it photo instead of image, like in the other RDS?

**Comment by sumutcan** [comment]
> 2.6 contactPoint - what does contact point mean in this context?

it is for contact possibilities for different purposes. e.g., phone numbers for reservation, conventions, accounting etc.
