### ISSUE TITLE
[RC] POI

### ISSUE THREAD

**Issue by eliaskaerle** [ODTA/ds#13]
This is the RC (Request for Comments) for the POI RDS. Please use the comments section below for discussions.

RDS Abstract:
In this RDS we propose a Domain Specification (DS) for points of interest (POIs), based on schema.org/Place or odta:PointOfInterest respectively, as used in the GNTB’s “Knowledge Graph für den Deutschlandtourismus” project. The DS holds all properties required to annotate a POI sufficiently using the vocabulary of schema.org and the extension of odta:PointOfInterest. To annotate the type of license applied to the data set, we suggest additionally modifying the original schema.org vocabulary.

Link to RC: https://github.com/ODTA/ds/blob/main/docs/rc/POIDS-RC-RDS.pdf
Link to RC's DS representation: https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=Vcw4gpF9s

**Comment by asolvo** [comment]
smokingAllowed not necessary IMHO. 
Smoking is regulated in general as a national law, e.g. you must not smoke in a restaurant. No need to specify it in the POI-schema.

**Comment by asolvo** [comment]
faxNumber not necessary IMHO. 
Deprecated. No need to send a fax to the Brandenburger Tor.

**Comment by sumutcan** [comment]
is this really the case in entire Dach area? no exceptions?

> smokingAllowed not necessary IMHO. Smoking is regulated in general as a national law, e.g. you must not smoke in a restaurant. No need to specify it in the POI-schema.

**Comment by asolvo** [comment]
> is this really the case in entire Dach area? no exceptions?
> 
> > smokingAllowed not necessary IMHO. Smoking is regulated in general as a national law, e.g. you must not smoke in a restaurant. No need to specify it in the POI-schema.

In Germany, Italy, Austria and Switzerland. 
Anyway - if you think the smokingAllowed makes sense, then also no problem for me

**Comment by FabianBerner1** [comment]
I would propose a few more new properties for features a poi can offer. Things like dogs/pets allowed, internet access, WLAN Hotspot, etc. are missing. It could make sense to add something like [LocationFeatureSpecification](https://schema.org/LocationFeatureSpecification) to either LocalBusiness or PointOfInterest, but with a focus on general features of a place and not only for amenities of accommodations.

**Comment by FabianBerner1** [comment]
Same with information about hygiene, i can't find any properties for this. I can only find the possibility to declare bathrooms with the Accommodation type. But other POIs can have bathrooms too.

**Comment by FabianBerner1** [comment]
At 2.6 new property: Event
I strongly think more than 1 event should be able to be referenced here.

**Comment by FabianBerner1** [comment]
as stated in [RC] Accommodation/LodgingBusiness #3 i would propose to add accessibility features to POI as well. It makes sense to add these Information to general POIs as well, as [Reisen für Alle](https://www.reisen-fuer-alle.de) is specified for not only accommodations but general POIs too

**Comment by FabianBerner1** [comment]
I propose another new proprty: TrustYouID
[Trust You ](https://www.trustyou.com/de/) streamlines reviews for destinations, so it would be good to offer a clean way to identify the specify entities with the ID. 
Or should this be somehow implemented as an additional identifier as a PropertyValue?

**Comment by FabianBerner1** [comment]
how would one add a reference to a trail? It would make sense to be able to reference a related trail with a property like: relatedTrail. This way a trail which has to do with the POI contentwise can be referenced.

**Comment by asolvo** [comment]
@FabianBerner1 I don't agree on a dedicated property for a proprietary service like TrustYou. 
However, if we would want to integrate references to rating services then it would make sense to do so not only for POIs, but also for lodging, events, trail, touristattraction, etc.

**Comment by sumutcan** [comment]
> 



> I would propose a few more new properties for features a poi can offer. Things like dogs/pets allowed, internet access, WLAN Hotspot, etc. are missing. It could make sense to add something like [LocationFeatureSpecification](https://schema.org/LocationFeatureSpecification) to either LocalBusiness or PointOfInterest, but with a focus on general features of a place and not only for amenities of accommodations.

this can be modelled with the existing additionalProperty property. because it was already foreseen that many individual properties from different LMOs may be needed to describe a POI.

**Comment by sumutcan** [comment]
> Same with information about hygiene, i can't find any properties for this. I can only find the possibility to declare bathrooms with the Accommodation type. But other POIs can have bathrooms too.

can be modelled with containsplace.

**Comment by sumutcan** [comment]
> as stated in [RC] Accommodation/LodgingBusiness #3 i would propose to add accessibility features to POI as well. It makes sense to add these Information to general POIs as well, as [Reisen für Alle](https://www.reisen-fuer-alle.de) is specified for not only accommodations but general POIs too

this is taken care of by another working group

**Comment by sumutcan** [comment]
> how would one add a reference to a trail? It would make sense to be able to reference a related trail with a property like: relatedTrail. This way a trail which has to do with the POI contentwise can be referenced.

if a POI is on a trail, can be connected with the containedInPlace property to that Trail.

**Comment by FabianBerner1** [comment]
> > 
> 
> > I would propose a few more new properties for features a poi can offer. Things like dogs/pets allowed, internet access, WLAN Hotspot, etc. are missing. It could make sense to add something like [LocationFeatureSpecification](https://schema.org/LocationFeatureSpecification) to either LocalBusiness or PointOfInterest, but with a focus on general features of a place and not only for amenities of accommodations.
> 
> this can be modelled with the existing additionalProperty property. because it was already foreseen that many individual properties from different LMOs may be needed to describe a POI.

I think the availability of a WLAN Hotspot is too important for touristic places to be covered by an additionalProperty. 
For dogs/pets allowed and other things in a LocationFeatureSpecification I can agree that additionalPropertys can be used to not get a too diverse Property

**Comment by FabianBerner1** [comment]
> > Same with information about hygiene, i can't find any properties for this. I can only find the possibility to declare bathrooms with the Accommodation type. But other POIs can have bathrooms too.
> 
> can be modelled with containsplace.

I agree on the bathrooms, but other things from the hygiene domain are still missing. To specify what I mean some examples: digitale Gästeregistrierung vor Ort, Hand-Desinfektionsspender in öffentlichen Bereichen, Kontaktloser Ckeck-In/ Check-Out, Kontaktloses Bezahlen, Lüftungskonzept und / oder Hochleistungsfiltergeräte vorhanden, Zeitfenster Ticketshop

These examples resulted from the corona pandemic and became somewhat important for tourists visiting POIs, so I think we should add some Property where they fit in

**Comment by sumutcan** [comment]
> > > Same with information about hygiene, i can't find any properties for this. I can only find the possibility to declare bathrooms with the Accommodation type. But other POIs can have bathrooms too.
> > 
> > 
> > can be modelled with containsplace.
> 
> I agree on the bathrooms, but other things from the hygiene domain are still missing. To specify what I mean some examples: digitale Gästeregistrierung vor Ort, Hand-Desinfektionsspender in öffentlichen Bereichen, Kontaktloser Ckeck-In/ Check-Out, Kontaktloses Bezahlen, Lüftungskonzept und / oder Hochleistungsfiltergeräte vorhanden, Zeitfenster Ticketshop
> 
> These examples resulted from the corona pandemic and became somewhat important for tourists visiting POIs, so I think we should add some Property where they fit in

can all these be modeled as potential values for the amenity feature property, as LocationFeatureSpecification?

I think the word "amenity" covers all of these things, as it means "a desirable or useful feature or facility of a building or place". I will model this generically for now, we can then discuss in the feedback meeting with the others, if we need a property like "hygieneFeatures"

**Comment by richardhunkel** [comment]
Is it possible / useful to add an e-mail address? For PostalAddress there is the possibility: https://schema.org/PostalAddress. Fax, phone and URL are provided in the DS, e-mail address is not.
In this context, it should be specified how PoI is different from Local Business.  When does one use Local Business (e.g., when it costs money or when the owner is an organization?) and when POI? Or does it not matter?

**Comment by sumutcan** [comment]
> Is it possible / useful to add an e-mail address? For PostalAddress there is the possibility: https://schema.org/PostalAddress. Fax, phone and URL are provided in the DS, e-mail address is not. In this context, it should be specified how PoI is different from Local Business. When does one use Local Business (e.g., when it costs money or when the owner is an organization?) and when POI? Or does it not matter?

you can choose the type (or combinations of types) based on the nature of the POI. In principle, every POI is a Place (or a subtype of it.) It can be a Place and a Localbusiness, for example, if it provides services and products. The way we are currently modelling POIs allow data publishers to pick the right type based on the nature of the POI. If you have a mountain, then you can use the Mountain type, if you have a museum, you can use the Museum and LocalBusiness types together which allows you to use properties from both types.

in any case, we do not currently restrict the PostalAddress type in the range of schema:address, as this was not explicitly requested and there was no particular reason to restrict it. so the email property can be used if needed.
