### ISSUE TITLE
[RC] Trail

### ISSUE THREAD

**Issue by eliaskaerle** [ODTA/ds#14]
This is the RC (Request for Comments) for the Trail RDS. Please use the comments section below for discussions.

RDS Abstract:
In this RDS we propose a Domain Specification (DS) for Trails, based on schema.org/Place or odta:Trail respectively, as used in the GNTB’s “Knowledge Graph für den Deutschlandtourismus” project. The DS holds all properties required to annotate a trail sufficiently using the vocabulary of schema.org and the extension of odta:Trail. To annotate the type of license applied to the data set, we suggest additionally modifying the original schema.org vocabulary.

Link to RC: https://github.com/ODTA/ds/blob/main/docs/rc/TrailDS-RC-RDS.pdf
Link to RC's DS representation: https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=5cIVs0k-I

**Comment by asolvo** [comment]
odta:Trail contains a lot of POI attributes: 
there is an odta:startLocation and an odta:endLocation, and there are odta:wayPoints. 

Why do we need also a "geo" property to describe geo coordinates of the place? I think we do not neet this property.

**Comment by asolvo** [comment]
There is also a "address" property for a PostalAddress. I don't think we need this, no trail ever has got a postal address. You won't write a letter to a trail or route.

**Comment by asolvo** [comment]
I would suggest additional attributes for odta:Trail:

- trail length [km]  
- duration of the trail (to walk, to bike, to drive) 
- highest point [meters above sea level] 
- altitude uphill [in height meters]
- difficulty level [1-6]
- circular trail [yes|no] ("Rundwanderung")

**Comment by asolvo** [comment]
The "difficulty level" attribute of odta:Trail could be based on SAC scale for hiking. There are 6 levels ranging from 1 to 6.
In fact there is no international standard for the classification of [hiking|biking|mountaineering|climbing|snowshoe|skitour] trails. However, the SAC scale is used in Wikipedia and in OpenStreetMap.

Sources: 
https://wiki.openstreetmap.org/wiki/DE:Key:sac_scale
https://de.wikipedia.org/wiki/SAC-Wanderskala 
https://de.wikipedia.org/wiki/SAC-Schneeschuhtourenskala

**Comment by sumutcan** [comment]
> There is also a "address" property for a PostalAddress. I don't think we need this, no trail ever has got a postal address. You won't write a letter to a trail or route.

to me this is a fair point

**Comment by giggei** [comment]
Hi, I am with @asolvo and would suggest to add the following attributes to Trail (adding the respective downhill parts)

- length (m)
- duration of the trail (to walk, to bike, to drive)
- highest point [meters above sea level]
- **lowest point [meters above sea level]**
- altitude uphill [in height meters]
- **altitude downhill [in height meters]**
- circular trail [yes|no] ("Rundwanderung")


For difficulty the alignement with the  SAC scale  sounds reasonable but may lead to confusion if it is just a number/level.
For example outdooractive uses a scale of only 3 levels.
Also most guideposts by the Alpenverein use three levels (blue, red, black).

Maybe we might add some categories for that (with speaking enumerations to prevent confusion about numbers)

- difficulty (enum: easy, medium, hard)
- physical condition
- equipmentNeeded

Also accessability might be relevant:

- accessableByBabyBuggy

Regards
Markus

**Comment by asolvo** [comment]
@Markus: I agree on accessableByBabyBuggy 
--> We will work on accessability properties in the ODTA accessability sub-group. 
See [miro board](https://miro.com/app/board/uXjVOSB3hTk=/)

**Comment by giggei** [comment]
@asolvo In Germany there is kind of a stadard for accessability by "Reisen für Alle" : https://www.reisen-fuer-alle.de/qualitaetskriterien_312.html
But that is focused on people with handicaps.
So a **accessableByBabyBuggy** does not fall directly into this approch. ~~But maybe you can add the "Reisen für Alle" to the miro board.~~ Just saw it is already there.

**Comment by asolvo** [comment]
@giggei Yes, the proposal of the ODTA group on accessability will be based on "Reisen für alle". 
In brief, we will have two levels of accessability: Level 1 = specify yourself as accessible, Level 2 = You have a certificate from an inspection organization

**Comment by asolvo** [comment]
@giggei difficulty is difficult! ;-) 

> difficulty (enum: easy, medium, hard) 
These 3 levels are standard in Germany and Austria, but not in Switzerland. In the Austrian provices the different level are named differently. Some regions also use yellow for "Talwege". In CH there is the SAC scale with 7 levels. The SAC scale is also used in Wikipedia and OSM --> so 7 levels is a global standard for trails. 
We want the DS for "trail" to be adaptable for different sport trails like hiking, biking, skimo, .... so also difficulty has to be a usable standard. 
I would therefore suggest the 7 level SAC scale for difficulty, which then can be mapped to the 3 levels easy, medium, hard. 

Sources:
https://akademie.alpinewelten.com/bergwandern/klassifizierung-von-wanderwegen 
https://www.alpenverein.at/portal/huetten-wege/wegenetz/wegekategorien/index.php 
https://www.sac-cas.ch/fileadmin/Ausbildung_und_Wissen/Tourenplanung/Schwierigkeitsskala/Wanderskala-SAC.pdf  
https://www.bergwelten.com/lp/sac-schwierigkeitsskalen-wieso-warum-weshalb

**Comment by SunderlandNRW** [comment]
To 2.3. property address: I agree that including only one address can be a little exclusive to trails with different start and end points. I would suggest a DS (boolean) that clarifies whether it us a circular trail (e.g. https://www.sauerland.com/erleben/wandern/Sauerland-Spazierrunden/Briloner-Waldfeenpfad#/article/3d4e2d1f-bccd-4d6b-a207-48538717015e). In that case you might only need one address, in other cases minimum of 2 addresses.

**Comment by SunderlandNRW** [comment]
To 2.4 aggregateRating: "A trail has maximum one aggregateRating value." Why only maximum one value? Value in terms of 1-5 Stars or rating categories such as panorama or conditions? We e.g. allow more than one rating category for a trail.
![image](https://user-images.githubusercontent.com/105437473/204247793-b04c12be-8fc7-4271-837c-d502a52c7d3f.png)

**Comment by SunderlandNRW** [comment]
2.5. ContainedInPlace okay, can there be more than one? e.g. Rheinradweg running through lots of German states.

**Comment by SunderlandNRW** [comment]
2.6. containsPlace - is this automatically filled by analysing geo locations from schema:TouristAttraction? Or would we need to map information?
What is the difference to 2.20 wayPoint?

**Comment by SunderlandNRW** [comment]
2.14 potentialAction - I do not believe a restriction is sensible. Neither ExerciseAction nor TravelAction will be 100% correct. Yes it is a type of exercise to walk or bike and you are moving, potentially travelling, but in a sense of tourism it could also be described as a leisureAction or recreationalAction, if there is something similar.

**Comment by SunderlandNRW** [comment]
What about level of difficulty and other criteria (family/animal-friendly)?

**Comment by SunderlandNRW** [comment]
2.18. typeOfTrail - A canonical list of the trail types that could be defined as enumeration members by ODTA - suggestion: 
**Hiking**
- Hike
- Long-distance hike
- Pilgrimage trail
- Thematic trail
- Sightseeing trail
**Biking**
- Bike tour
- Mountainbike tour
- Mountainbike tour transalpine
- Racing bike tour
**Walking and Skating**
- Nordic Walking
- Jogging
- Trail running
- Inline skating
**Climbing**
- Via Ferrata
- Mountain tour
- Alpine tour
- Alpine climbing
**Winter Trail**
- Winter hike
- Toboggan run
- Ski tour
- Snow show hike
- Cross-country skiing
- Ski Freeride
- Ice Climbing
- Ski round tour
- Ice skating
**Water trail**
- Canyoning
- Canoe
- Kayak
**Horse Trail**
- Carriage ride
- Horse riding
- Horse-drawn sleigh
**Motorised Trail**
- Panorama
- Camper Van
- Motorcycle
- Offroad

**Comment by asolvo** [comment]
>2.18. typeOfTrail - A canonical list of the trail types that could be defined as enumeration members by ODTA 
Please also add **Culinary trail**. 
@SunderlandNRW Isn't "horse trail" the same as "horse riding"?

**Comment by SunderlandNRW** [comment]
@asolvo horse trail would be the main category and horse riding the subcategory. Like Biking and Bike Tour or Hiking and Hike

**Comment by SunderlandNRW** [comment]
> > 2.18. typeOfTrail - A canonical list of the trail types that could be defined as enumeration members by ODTA
> > Please also add **Culinary trail**.
> > @SunderlandNRW Isn't "horse trail" the same as "horse riding"?

@asolvo horse trail would be the main category and horse riding the subcategory. Like Biking and Bike Tour or Hiking and Hike

**Comment by richardhunkel** [comment]
Hi, a general question - not specific to the proposed extensions: Sometimes there are alternative routes to trails (e.g. if a section is closed), access routes or shortcuts. How can these be represented in the DS?

**Comment by SunderlandNRW** [comment]
> Reference in

Maybe a boolean DiversionInPlace yes or no. With an extra text or geoshape element?

**Comment by SunderlandNRW** [comment]
> Hi, a general question - not specific to the proposed extensions: Sometimes there are alternative routes to trails (e.g. if a section is closed), access routes or shortcuts. How can these be represented in the DS?

Maybe a boolean DiversionInPlace yes or no. With an extra text or geoshape element?

**Comment by sumutcan** [comment]
> To 2.3. property address: I agree that including only one address can be a little exclusive to trails with different start and end points. I would suggest a DS (boolean) that clarifies whether it us a circular trail (e.g. https://www.sauerland.com/erleben/wandern/Sauerland-Spazierrunden/Briloner-Waldfeenpfad#/article/3d4e2d1f-bccd-4d6b-a207-48538717015e). In that case you might only need one address, in other cases minimum of 2 addresses.

there is startLocation and endLocation properties already. this should cover it.

**Comment by sumutcan** [comment]
> 

this is interesting and probably would need a seperate proposal as you indicate :)
from the top of my head, we might need to define trails more fine-grained with a property called hasSection for example. this is then also a "trail" with a different start and end point. Then we can describe these sections in different ways, like if they are closed or not.

would be beneficial to see an example though.

**Comment by sumutcan** [comment]
> 2.5. ContainedInPlace okay, can there be more than one? e.g. Rheinradweg running through lots of German states.

this is in principle possible.

**Comment by sumutcan** [comment]
> 2.6. containsPlace - is this automatically filled by analysing geo locations from schema:TouristAttraction? Or would we need to map information? What is the difference to 2.20 wayPoint?

this is actually a very good point. maybe @richardhunkel or @eliaskaerle  can tell if they had a different use for these two properties.

**Comment by sumutcan** [comment]
> Hi, I am with @asolvo and would suggest to add the following attributes to Trail (adding the respective downhill parts)
> 
> * length (m)
> * duration of the trail (to walk, to bike, to drive)
> * highest point [meters above sea level]
> * **lowest point [meters above sea level]**
> * altitude uphill [in height meters]
> * **altitude downhill [in height meters]**
> * circular trail [yes|no] ("Rundwanderung")
> 
> For difficulty the alignement with the SAC scale sounds reasonable but may lead to confusion if it is just a number/level. For example outdooractive uses a scale of only 3 levels. Also most guideposts by the Alpenverein use three levels (blue, red, black).
> 
> Maybe we might add some categories for that (with speaking enumerations to prevent confusion about numbers)
> 
> * difficulty (enum: easy, medium, hard)
> * physical condition
> * equipmentNeeded
> 
> Also accessability might be relevant:
> 
> * accessableByBabyBuggy
> 
> Regards Markus

sounds like a good suggestion to me

**Comment by eliaskaerle** [comment]
> 2.6. containsPlace - is this automatically filled by analysing geo locations from schema:TouristAttraction? Or would we need to map information? What is the difference to 2.20 wayPoint?


> is this automatically filled by analysing geo locations from schema:TouristAttraction

no. here we just define it for the DS. filling it (automatically) is up to the application implementation.

> Or would we need to map information?

yes, if an application wants to use that property, then it must be mapped. e.g Hotel.containsPlace Bar. For a trail I can not think of a use case... But is up to the data provider to map it accordingly.

> What is the difference to 2.20 wayPoint

Way points are places along the trail. So actually ON the trail. Like a e-charging-stagion for e-bikes. or a restaurant...

**Comment by sumutcan** [comment]
> > What is the difference to 2.20 wayPoint
> 
> Way points are places along the trail. So actually ON the trail. Like a e-charging-stagion for e-bikes. or a restaurant...

@eliaskaerle  I still do not understand it. containsPlace means also that the place is on the trail (i.e., the trail contains the place)

**Comment by sumutcan** [comment]
> > 
> 
> this is interesting and probably would need a seperate proposal as you indicate :) from the top of my head, we might need to define trails more fine-grained with a property called hasSection for example. this is then also a "trail" with a different start and end point. Then we can describe these sections in different ways, like if they are closed or not.
> 
> would be beneficial to see an example though.

the "trail sections" I would leave for a second round of submission as it might a bit more complex than just adding a property.

**Comment by sumutcan** [comment]
@eliaskaerle @richardhunkel @SunderlandNRW @giggei 
Here is the draft DS for your preview:
https://odta.sti2.org/?dsb-list=7Kk-V4zwE&dsb-ds=LqyqEc9e5

some decisions I made: 
- I used the SAC scale for now, as it looked more granular and I was convinced by @asolvo's arguments. but the way it is defined is flexible, we can easily add another scale if needed later.
- the trail type enumerations from @SunderlandNRW will be added in the draft document, just not visible currently on the overview.
- as mentioned earlier, trail sections part is left for now for a future submission. related to that, the containsPlace property is removed for now as wayPoint covers it.
- address and geo properties are also removed due to start and end location properties.
- some new properties added, following the discussion.
- ExerciseAction is left at the moment in the range of potentialAction, as the purpose of that property to specify any sport activities that can be done on the trail. if there are concrete examples that other actions are needed, we can do an update.

**Comment by sumutcan** [comment]
as we did with event, I'd like to propose a short meeting for a final agreement on the DraftDS

Please fill the doodle until 20.01.2023, if you wish to participate: https://doodle.com/meeting/participate/id/bk22WGva

@eliaskaerle @richardhunkel @giggei @SunderlandNRW and anyone else who is interested

**Comment by sumutcan** [comment]
note that geo property has been added back because it is needed to build the trail on a map.
