### ISSUE TITLE
[RC] Event

### ISSUE THREAD

**Issue by eliaskaerle** [ODTA/ds#15]
This is the RC (Request for Comments) for the Event RDS. Please use the comments section below for discussions.

RDS Abstract:
In this RDS we propose a Domain Specification (DS) for events, based on schema.org/Event, as used in the GNTB’s “Knowledge Graph für den Deutschlandtourismus” project. The DS holds all properties required to annotate an event sufficiently using just the vocabulary of schema.org. However, to annotate the type of license applied to the data set we suggest modifying the original schema.org vocabulary.

Link to RC: https://github.com/ODTA/ds/blob/main/docs/rc/EventDS-DZT-RC-RDS.pdf
Link to RC's DS representation: https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=7EFu1oAZC

**Comment by SunderlandNRW** [comment]
Approving 2.2 schema:audience in terms of kids, teenagers, adults, seniors/pensioners for front end filtering. We should discuss if audience attributes like Sinus Milieus make sense for future backend filtering? Possibly an additional property schema: targetGroup?

**Comment by SunderlandNRW** [comment]
2.6 Is schema:duration really necessary if there is a date and time of start, door time and endDate?

**Comment by SunderlandNRW** [comment]
2.9 schema:eventSchedule - can every event schedule be described in a standardised form? How many boxes will there need to be? Looking at the examples at https://schema.org/eventSchedule I am not quite sure if we need schema:eventSchedule or if all information can already be found in date and time of start, door time and endDate or vice versa?
Wouldn't we just need to link single events to create an event series?

**Comment by SunderlandNRW** [comment]
2.11 schema:identifier would that be a link to the official event website, or what else is meant with an identifier?

**Comment by SunderlandNRW** [comment]
2.15 schema:location  - is schema:location able to link the event to an already existing POI? Or will the Knowledge Graph differentiate between POI and location for event purposes in future?

**Comment by SunderlandNRW** [comment]
2.17 schema:offers

https://schema.org/Offer shows a vast number of properties, e.g. also "isFamilyFriendly". Will we be including schema:offers completely as a section in an event, so these information will need to be filled in/ transmitted twice or can there be a link between attributes?

**Comment by SunderlandNRW** [comment]
2.20 what would an example for schema:potentialAction be? https://schema.org/potentialAction doesn't give it away.

**Comment by SunderlandNRW** [comment]
2.22 schema:review - where would this information be coming from? Automatically from Google reviews or Tripadvisor etc.? or our Data Hubs? 
![image](https://user-images.githubusercontent.com/105437473/200533614-10f72346-d6d6-4c6b-94f1-c663d9df3249.png)

**Comment by SunderlandNRW** [comment]
2.23 schema:sameAs - this would be the link between single events to create an event series, correct? Could on get a summary of all the events "sameAs" somehow?

**Comment by SunderlandNRW** [comment]
2.24 schema:sdLicense - What is the technical recommendation for the future? Some states apply a CC0 licence to the main data set and then give separate licences to texts and images. We currently have not got the distinction between the main data set and text, but at least separate licencing for images. What would the official recommendation be here? How does schema.org handle it normally? What are pros and cons? Ideally we should find a joint solution.

As we have now figured with our POI licence information we would definitely need to not only have sdLicense, but also sdPublisher und sdDatePublished.

**Comment by SunderlandNRW** [comment]
> 2.23 schema:sameAs - this would be the link between single events to create an event series, correct? Could on get a summary of all the events "sameAs" somehow?

2.27 schema:subEvent makes sense, as it is still different to an event series. The head event could be like an art festival and a subevent one of the exhibitions. An event series would be described by schema:sameAs, so we would support both requests.

**Comment by SunderlandNRW** [comment]
> 

2.28 schema:superEvent - interesting name but obviously necessary to work with 2.27 subEvent.

**Comment by SunderlandNRW** [comment]
2.29 schema:typicalAgeRange 
Did not understand neither https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal nor the necessity of a non-standardised text for age groups. Wouldn't it be enought to include an enumeration of age-groups with 2.2 audience?

**Comment by SunderlandNRW** [comment]
> 

2.30 what is the difference between 2.11 schema:identifier and 2.30 schema:url - why do we need both?

**Comment by SunderlandNRW** [comment]
I am afraid the link to the RCs DS isn't working with me https://odta.sti2.org/7EFu1oAZC  
![image](https://user-images.githubusercontent.com/105437473/200540921-1f91b997-c912-413f-9273-6ea09e075579.png)

As I can't say whether that has happened: Would it be possible or useful to combine the representations of DS for the same types (like Event by odta and Event by DZT) to get an overview of what a final DS would look like?

**Comment by SunderlandNRW** [comment]
> As I can't say whether that has happened: Would it be possible or useful to combine the representations of DS for the same types (like Event by odta and Event by DZT) to get an overview of what a final DS would look like?

Looking at the Issue by the working group Event of the ODTA, this RDS has basically described the properties in detail, that had been depicted in a table by the other group. With this in mind, commenting and referring to RDS for the same data type would have been much easier in a joint RDS.

**Comment by FabianBerner1** [comment]
What about inactive Events? These can be important to still have available but can`t be flagged as such as of now
A new Property: Status could be added with a boolean value for active or inactive.

The Property EventStatus would not fit because these are referring to the event as the event thats taking place, not the event that is to be exported.

**Comment by FabianBerner1** [comment]
> 2.11 schema:identifier would that be a link to the official event website, or what else is meant with an identifier?

this Property identifier ist meant for unique values to identify the Event with, like an ID

**Comment by FabianBerner1** [comment]
Spendenlinks can`t be mapped as of now, would it be advisable to add another Property: donationLink ?

**Comment by FabianBerner1** [comment]
Events can´t have a specific type of season / Saisonale Zuordnung at the moment, 
I propose a new Property: eventSeason of the datatype season
which would be an enumeration with members like: easter, ascension day, pentecost, halloween, christmas, silvester

**Comment by FabianBerner1** [comment]
Things like virtual events and (non) touristic events cant be mapped as of now.
These could be added to the Property EvenStatusType, but at the moment there are only enumeration members to express if the event is postponed, etc. The member EventMovedOnline isn't the same as a virtual event, as it implies that the event was once planned to be at a location.
A new Property would be good to add these Keywords as enumeration members, there could also be other members added which would have to be discussed.

**Comment by FabianBerner1** [comment]
> Things like virtual events and (non) touristic events cant be mapped as of now. These could be added to the Property EvenStatusType, but at the moment there are only enumeration members to express if the event is postponed, etc. The member EventMovedOnline isn't the same as a virtual event, as it implies that the event was once planned to be at a location. A new Property would be good to add these Keywords as enumeration members, there could also be other members added which would have to be discussed.

2.10 EventStatusType is missing an enumeration member for EventBookedOut or EventSoldOut

**Comment by FabianBerner1** [comment]
The possibility to add additional or general information for prices would be good.
e.g.: voluntary donation appreciated

As a new Property: AdditionalPricingNote or AdditionalPricingInformation as Text

**Comment by FabianBerner1** [comment]
![image](https://user-images.githubusercontent.com/117816182/200820031-67946d66-6c84-411f-a442-6e6e10fe6530.png)

2.29 typicalAgeRange
It would make sense to add this Property to the PriceSpecification class as well (maybe with name: AgeRange).
This way multiple prices can be added to an event and each can have a specific AgeRange identified with them. (One Price for children 5-12, one for adults 18-60, etc.)

Would it not be advisable to add another Value Datatype Where the 2 ages can be placed as Integer Values?
Like: New Datatype "Range" or AgeRange with 2 Values "From" and "To" as Integers

**Comment by SunderlandNRW** [comment]
> What about inactive Events? These can be important to still have available but can`t be flagged as such as of now A new Property: Status could be added with a boolean value for active or inactive.
> 
> The Property EventStatus would not fit because these are referring to the event as the event thats taking place, not the event that is to be exported.

What would you describe as an inactive event? Something like a Christmas market that only takes place at a certain time? Events that are over shouldn't be displayed any longer, should they? Thus the event will pop up again once the data set owner has updated the date again. Not sure whether we need inactive event then. What do you mean with "not the event that is to be exported"?

**Comment by SunderlandNRW** [comment]
> Spendenlinks can`t be mapped as of now, would it be advisable to add another Property: donationLink ?

Nothing that we have had an eye on so far. How many events relevant to tourism collect donations? Especially in advance..

**Comment by SunderlandNRW** [comment]
> Events can´t have a specific type of season / Saisonale Zuordnung at the moment, I propose a new Property: eventSeason of the datatype season which would be an enumeration with members like: easter, ascension day, pentecost, halloween, christmas, silvester

Where do we stop? What about hanukkha, diwali, etc. Maybe to keep it simple we could stick to the temperate and polar seasons: Spring, Summer, Autumn and Winter, in addition to the months? Or we need a DS with a text box to include tags for special marketing purpose or similar.

**Comment by SunderlandNRW** [comment]
> Things like virtual events and (non) touristic events cant be mapped as of now. These could be added to the Property EvenStatusType, but at the moment there are only enumeration members to express if the event is postponed, etc. The member EventMovedOnline isn't the same as a virtual event, as it implies that the event was once planned to be at a location. A new Property would be good to add these Keywords as enumeration members, there could also be other members added which would have to be discussed.

I think this can be found in the proposal in 2.8. schema:eventAttendanceMode

**Comment by SunderlandNRW** [comment]
> The possibility to add additional or general information for prices would be good. e.g.: voluntary donation appreciated
> 
> As a new Property: AdditionalPricingNote or AdditionalPricingInformation as Text

Don't think it's a bad idea. However I am trying to think how this text box will be used. Probably less machine-readable. What other information would be included in this text box? If there is nothing we can think of, maybe we could use a boolean true or false schema:DonationsWelcome? Or does a boolean always need to be checked either or (mandatory)? Is there an optional check box?

**Comment by SunderlandNRW** [comment]
> ![image](https://user-images.githubusercontent.com/117816182/200820031-67946d66-6c84-411f-a442-6e6e10fe6530.png)
> 
> 2.29 typicalAgeRange It would make sense to add this Property to the PriceSpecification class as well (maybe with name: AgeRange). This way multiple prices can be added to an event and each can have a specific AgeRange identified with them. (One Price for children 5-12, one for adults 18-60, etc.)
> 
> Would it not be advisable to add another Value Datatype Where the 2 ages can be placed as Integer Values? Like: New Datatype "Range" or AgeRange with 2 Values "From" and "To" as Integers



> 2.29 schema:typicalAgeRange Did not understand neither https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal nor the necessity of a non-standardised text for age groups. Wouldn't it be enought to include an enumeration of age-groups with 2.2 audience?


The self-inserted age groups could be a good idea @FabianBerner1 - might be more inclusive or rather gives more potential to individualise the data set, rather than my idea with set age groups as enumeration under audience. Couldn't we include the Value boxes in the DS schema:audience?

**Comment by FabianBerner1** [comment]
> > What about inactive Events? These can be important to still have available but can`t be flagged as such as of now A new Property: Status could be added with a boolean value for active or inactive.
> > The Property EventStatus would not fit because these are referring to the event as the event thats taking place, not the event that is to be exported.
> 
> What would you describe as an inactive event? Something like a Christmas market that only takes place at a certain time? Events that are over shouldn't be displayed any longer, should they? Thus the event will pop up again once the data set owner has updated the date again. Not sure whether we need inactive event then. What do you mean with "not the event that is to be exported"?

It can be important to show data in case they are referenced like a superEvent with 5 subEvents or when other types of content are referenced and inactive at the moment. 
These are explicitly not deleted elements to be still shown, but only inactive temporarily

**Comment by FabianBerner1** [comment]
I propose another way to represent dates and times in an event.
At the moment, each event can only take place at one time and day and have one fixed duration. Irregular Events or Events that are on mulitple different dates ( e.g. Shows on 2 following weekends) would all need to be representet as a different event entirely, even if all data is the same and there are only more than one times the event takes place.

I would add a new Property: "eventDates", which holds an amount of n Elements of a new Datatype "date" or "appointment"
The new Datatype would hold the information for: startDate, endDate, duration, eventStatus (from 2.10)

**Comment by FabianBerner1** [comment]
I propose to add a new Property to the Event class named: "relatedLink" with the Datatype relatedLink (https://schema.org/relatedLink)
With this, additional Links such as Links to Videos regarding the Event, Audio regarding the Event, Links for additional information, Links for live streams can be given.

It would have to be discussed if the relatedLink Datatype would benefit from another Property "LinkType" as Text, where the type of Link can be given.

**Comment by sumutcan** [comment]
> I propose another way to represent dates and times in an event. At the moment, each event can only take place at one time and day and have one fixed duration. Irregular Events or Events that are on mulitple different dates ( e.g. Shows on 2 following weekends) would all need to be representet as a different event entirely, even if all data is the same and there are only more than one times the event takes place.
> 
> I would add a new Property: "eventDates", which holds an amount of n Elements of a new Datatype "date" or "appointment" The new Datatype would hold the information for: startDate, endDate, duration, eventStatus (from 2.10)

https://schema.org/EventSeries - is this what you want to have @FabianBerner1 ? I think this is more complex than we think so I would actually consider this as a seperate submission. eventSchedule property could be also used for this purpose.

**Comment by sumutcan** [comment]
> I am afraid the link to the RCs DS isn't working with me https://odta.sti2.org/7EFu1oAZC ![image](https://user-images.githubusercontent.com/105437473/200540921-1f91b997-c912-413f-9273-6ea09e075579.png)
> 
> As I can't say whether that has happened: Would it be possible or useful to combine the representations of DS for the same types (like Event by odta and Event by DZT) to get an overview of what a final DS would look like?

I will do exactly this when I prepare the DraftDS after discussions.

**Comment by sumutcan** [comment]
> 2.15 schema:location - is schema:location able to link the event to an already existing POI? Or will the Knowledge Graph differentiate between POI and location for event purposes in future?

you can already link an existing POI to an Event via a location, as POIs are also Place instances.

**Comment by sumutcan** [comment]
> What about inactive Events? These can be important to still have available but can`t be flagged as such as of now A new Property: Status could be added with a boolean value for active or inactive.
> 
> The Property EventStatus would not fit because these are referring to the event as the event thats taking place, not the event that is to be exported.

not sure if I fully understand what you mean here, but sounds like a flag that is mostly for internal use. I would keep this out from a DS.

**Comment by sumutcan** [comment]
> > Things like virtual events and (non) touristic events cant be mapped as of now. These could be added to the Property EvenStatusType, but at the moment there are only enumeration members to express if the event is postponed, etc. The member EventMovedOnline isn't the same as a virtual event, as it implies that the event was once planned to be at a location. A new Property would be good to add these Keywords as enumeration members, there could also be other members added which would have to be discussed.
> 
> 2.10 EventStatusType is missing an enumeration member for EventBookedOut or EventSoldOut

this can be represented with the offer property and Offer type used in the other event submission #5 .
see here: https://schema.org/ItemAvailability

**Comment by sumutcan** [comment]
> 2.11 schema:identifier would that be a link to the official event website, or what else is meant with an identifier?

no, see the Zwischenbericht.

**Comment by sumutcan** [comment]
> 

sameAs is used to specify events that are the same as the described event, typically published by another source. it is used to link two different sources for the same instance.

**Comment by sumutcan** [comment]
> > The possibility to add additional or general information for prices would be good. e.g.: voluntary donation appreciated
> > As a new Property: AdditionalPricingNote or AdditionalPricingInformation as Text
> 
> Don't think it's a bad idea. However I am trying to think how this text box will be used. Probably less machine-readable. What other information would be included in this text box? If there is nothing we can think of, maybe we could use a boolean true or false schema:DonationsWelcome? Or does a boolean always need to be checked either or (mandatory)? Is there an optional check box?

this is already covered by the offers property. the donation situation can be added to the description of the offer. I am not against the property suggestion donationLink though.

**Comment by sumutcan** [comment]
> ![image](https://user-images.githubusercontent.com/117816182/200820031-67946d66-6c84-411f-a442-6e6e10fe6530.png)
> 
> 2.29 typicalAgeRange It would make sense to add this Property to the PriceSpecification class as well (maybe with name: AgeRange). This way multiple prices can be added to an event and each can have a specific AgeRange identified with them. (One Price for children 5-12, one for adults 18-60, etc.)
> 
> Would it not be advisable to add another Value Datatype Where the 2 ages can be placed as Integer Values? Like: New Datatype "Range" or AgeRange with 2 Values "From" and "To" as Integers

I think this could be solved with the Offer type. let's move the discussion at #12

**Comment by sumutcan** [comment]
# Intermediary Results
## 1 Introduction

Here is a "Zwischenbericht". It took some time for me to figure out the best way to represent this to ignite the further discussion. Here is a try. I'll go via referencing the sections in RC. The agreed aspects are marked with white_check_mark and the aspects that need further discussion with warning .
I gave my opinion as much as possible whether a recommendation makes sense from my point of view (marked bold). Of course there are still certain things that needs to be discussed by domain experts.

Note that for the DraftDS Proposal, this issue will be merged with #5 .
## 2 Suggestions in RC

### 2.1 additionalType

:white_check_mark:  seems to be accepted

### 2.2 audience

:white_check_mark: Agreed on the usage.

Possible predefined values for the range should be discussed (kids, teenagers, adults). I would say for the first round we let data publishers to create their own Audience instances, if there is no strong preference towards defining canonical values.

### 2.3 contributor
:white_check_mark: No objections so far

### 2.4 description

:white_check_mark: No objections so far 

### 2.5 doorTime

:white_check_mark: No objections so far

### 2.6 duration
:warning: @SunderlandNRW asks if we need this property at all, as startDate and endDate would already give us this information. **I tend to agree.**

### 2.7 endDate

:white_check_mark: no objections, 
:warning: however additional options are suggested by @FabianBerner1 for event dates. **I think the eventSchedule property is enough for events that occur in multiple days or periodically.** We might later also consider EventSeries type.

### 2.8 eventAttendanceMode

:white_check_mark: So far accepted.

### 2.9 eventSchedule
:warning:  @SunderlandNRW asks if every event can schedule can be represented in a standardized form. I **believe the Schedule type used in the range is detailed enough to represent a schedule for any event. EventSeries could be an alternative to, but not considered in this submission. So I would say we keep the eventSchedule property.** 

### 2.10 eventStatus

:white_check_mark: agreed to use the property
:warning:  @FabianBerner1 recommends to add enumeration members to the range of this property such as SoldOut or BookedOut. **this can be represented with the offer property and Offer type used in the other event submission https://github.com/ODTA/ds/issues/5 .
see here: https://schema.org/ItemAvailability**

### 2.11 identifier
:warning:  this property is as I understand recommended to provide an identifier coming from an external system (e.g. a backoffice system that manages event)
I am not sure if this property should be part of a DS as its purpose looks more technical. @eliaskaerle do you foresee any other usage than just representing an internal identifier? we already have the url property also as @SunderlandNRW points out.

### 2.12 image
:white_check_mark: seems to be accepted.

### 2.13 inLanguage
:white_check_mark: seems to be accepted

### 2.14 isAccessibleForFree
:white_check_mark: seems to be accepted

### 2.15 location
:white_check_mark: seems to be accepted.

### 2.16 name
:white_check_mark: seems to be accepted

### 2.17 offers
:warning:  @SunderlandNRW asks for the scope of the property. in principle the use of the property is accepted. I would say the range of the Offer type should not be restricted as this was not requested.

### 2.18 organizer
:white_check_mark: seems to be accepted

### 2.19 performer

:white_check_mark: seems to be accepted

### 2.20 potentialAction
:warning:  @SunderlandNRW asks the purpose of the property on Event. This property is typically used to attach a booking engine URI to the event. **I'd say we keep it as an optional property for future-proofness.**

### 2.21 previousStartDate
:white_check_mark: seems to be accepted

### 2.22 review
:white_check_mark: the property seems to be accepted. 
:warning: @SunderlandNRW asks where the values for this property should come from. It can come from internal systems or external sources, however this is no really a concern of the DS.

### 2.23 sameAs
:white_check_mark: seems to be accepted. but purpose needs to be clarified.

### 2.24 sdLicense
:white_check_mark: seems to be accepted. My technical recommendation would be to use this on an instance and if any property value of that instance has different license, then redefine it there. For example a POI can have CC0, but if an image of the POI has CC-BY-SA, then that overrides for the image. 

### 2.25 sponsor
:white_check_mark: seems to be accepted

### 2.26 startDate
:white_check_mark: seems to be accepted

### 2.27 subEvent
 :white_check_mark: seems to be accepted

### 2.28 superEvent

:warning:  @SunderlandNRW questions the need of this property while we have subEvent. I**t could be useful to provide links between events both ways.** needs discussion.

### 2.29 typicalAgeRange
:warning:  @SunderlandNRW asks if this property really needed if we have schema:audience @eliaskaerle, any comments? **It may be necessary to give specific age ranges in some cases though.** needs discussion.

### 2.30 url
:white_check_mark: seems to accepted. 

:warning:  still need to see if we need both identifier and url. If one needs to go I would rather eliminate identifier. Note that url does not necessarily uniquely identify an event (although in most of the cases it should), it could be also a webpage where the event (and others) are described.

# Newly suggested types, properties and enumeration members
:warning: sdPublisher and sdDatePublished is also recommended for provenance information
:warning: a boolean property for specifying whether and event is inactive. this sounds like only for presentation purposes for individual systems, therefore I do not think it belongs to a DS.
:warning: a property for specifying donation links for events is requsted. something like donationLink. **sounds feasible. any comments?**
:warning: a property for "event seasons" is recommended. I think this can be covered with the odta:theme property offered in #5 .
:warning: a property called relatedLink is proposed, to add related material to a event. **I do not think a new property is needed for this as Event already has the property subjectOf and about. I recommend to add these to the DS.**

# Conclusion

Please let me know if I missed anything from the discussion above. If you want to comment on a part of this Zwischenbericht, just copy and paste it with the "blockquote" functionality of Github. You can see it among the buttons in the toolbar on top of thecomment box (next to the italic button).

**Comment by eliaskaerle** [comment]
> 2.11 identifier
warning this property is as I understand recommended to provide an identifier coming from an external system (e.g. a backoffice system that manages event)
I am not sure if this property should be part of a DS as its purpose looks more technical. @eliaskaerle do you foresee any other usage than just representing an internal identifier? we already have the url property also as @SunderlandNRW points out.

Correct, any identifier the data publisher wants to store to identify the dataset. I argue for keeping it in the DS as I would argue for keeping an ISBN in a book's DS or a GTIN for a product. True, it is a technical property but useful for tasks like duplication detection or any other kind of quality enrichment.

To me, a `url` and an `identifier` are fundamentally different things. A URL points to the event's website or any website the data provider wants to store for that event. An identifier could be an URL, but also any other kind of identification token depended on whatever system the data provider prefers to use,

**Comment by eliaskaerle** [comment]
> 2.29 typicalAgeRange
warning @SunderlandNRW asks if this property really needed if we have schema:audience @eliaskaerle, any comments? It may be necessary to give specific age ranges in some cases though. needs discussion.

This is a question the domain experts need to answer. I only can think of scenarios where the audiences are not fine-grained enough, and the `typicalAgeRange` property can provide more detailed information. I don't think it hurts to have a supplementary `typicalAgeRange` property, but I leave the discussion up to the people providing and using the data.

**Comment by SunderlandNRW** [comment]
> > 2.11 identifier
> > warning this property is as I understand recommended to provide an identifier coming from an external system (e.g. a backoffice system that manages event)
> > I am not sure if this property should be part of a DS as its purpose looks more technical. @eliaskaerle do you foresee any other usage than just representing an internal identifier? we already have the url property also as @SunderlandNRW points out.
> 
> Correct, any identifier the data publisher wants to store to identify the dataset. I argue for keeping it in the DS as I would argue for keeping an ISBN in a book's DS or a GTIN for a product. True, it is a technical property but useful for tasks like duplication detection or any other kind of quality enrichment.
> 
> To me, a `url` and an `identifier` are fundamentally different things. A URL points to the event's website or any website the data provider wants to store for that event. An identifier could be an URL, but also any other kind of identification token depended on whatever system the data provider prefers to use,

definitely agree with you now, @eliaskaerle :)

**Comment by sumutcan** [comment]
Since the deadline for the DS is end of January, I would like to create the draft DS as soon as possible to present to the vote of entire ODTA.

@SunderlandNRW @FabianBerner1 @eliaskaerle do you any comments on the Zwischenbericht? I recommend we have a short meeting in the second week of january (after 9.01.2023) and finalize the feedback. of course any other ODTA member is also welcome to join.

**Comment by SunderlandNRW** [comment]
> Since the deadline for the DS is end of January, I would like to create the draft DS as soon as possible to present to the vote of entire ODTA.
> 
> @SunderlandNRW @FabianBerner1 @eliaskaerle do you any comments on the Zwischenbericht? I recommend we have a short meeting in the second week of january (after 9.01.2023) and finalize the feedback. of course any other ODTA member is also welcome to join.

@sumutcan I'd be happy to take part in a short meeting. Anywhere between 10h and 13h on the 11.01. or from 14h onwards on the 12.01. would be good.
