### ISSUE TITLE
[RC] Sustainability

### ISSUE THREAD

**Issue by D-Workz** [ODTA/ds#16]
This is the RC (Request for Comments) for the Nachhaltigkeit RDS. Please use the comments section below for discussions.

RDS Abstract:
The requested domain specification is about extending various schema.org types with new properties to represent the knowledge about the sustainability features (e.g., whether they use local products and are close to public transportation) of various tourism related
entities. In the remainder of the document, we provide our suggestions in relation to the requests made in the RDS. We then conclude with a summary and some general remarks. 

Link to RC: https://github.com/ODTA/ds/blob/main/docs/rc/SustainabilityDS-RC-RDS.pdf
Link to RC's DS representation: https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=EW1mOkrR-

**Comment by asolvo** [comment]
I would suggest calling it "SustainabilityDS" instead of "NachhaltigkeitDS"

**Comment by sumutcan** [comment]
the discussion this domain specification is closed for now as a final domain specification is published. 

The domain specification introduced the odta:sustainabilityFeature property with a set of enumerations as potential values.
For example, for events:

https://semantify.it/list/CRkyvcqGqeUu?ds=BJfiOVFdvBak

The documents linked here are no longer relevant. Please open a new issue if you have any questions.
