### ISSUE TITLE
schema:makesOffer in der DS odta:PointOfInterest

### ISSUE THREAD

**Issue by dklinge** [ODTA/ds#19]
Eintrittspreise sind eine grundlegende Information für den Gast und für die Entscheidung zum Besuch eines PointOfInterest oft essenziell. Diese Information ist nicht weniger wichtig wir die Adresse, die Öffnungszeiten oder die URL.
Als Range kommt schema:Offer in Frage.

**Comment by sumutcan** [comment]
... schon berücksichtigt.
