### ISSUE TITLE
schema:containsPlace als Property in odta:PointOfInterest

### ISSUE THREAD

**Issue by dklinge** [ODTA/ds#20]
Oft stehen unterschiedliche touristische Einrichtungen in einer unmittelbaren räumlichen Beziehung. Eine Burg oder ein Schloss können ein Restaurant, ein Museum oder eine Veranstaltungsstätte enthalten. Dabei macht es sich oft erforderliche diese als einzelne Objekte anzulegen, da sich z.B. Öffnungszeiten, die Eintrittspreise oder die Betreiber unterscheiden. Um abzubilden welche Einrichtung zu einem solchen Objekt gehören ist es sich die Property schema:containsPlace in der DS odta:PointOfInterest bereitzustellen.

**Comment by sumutcan** [comment]
... schon berücksichtigt.
