### ISSUE TITLE
[RC] LocalBusiness

### ISSUE THREAD

**Issue by FabianBerner1** [ODTA/ds#21]
[LocalBusiness](https://schema.org/LocalBusiness) has a Property for payment information called [payment Accepted](https://schema.org/paymentAccepted) with Text as the expected datatype.
I propose to add the existing enumeration [PaymentMethod](https://schema.org/PaymentMethod) as another datatype. This way, standardized payment options can be used while handling an LocalBusiness as an MTE with PointOfInterest.

Other discussions about the LocalBusiness Type are welcome in this Issue as well.

## LocalBusiness

Fabian Berner

## What is the topic that should be discussed?
Extensions to the LocalBusiness Type
**URI of the existing schema from schema.org or ODTA:** https://schema.org/LocalBusiness

> [LocalBusiness](https://schema.org/LocalBusiness) has a Property for payment information called [payment Accepted](https://schema.org/paymentAccepted) with Text as the expected datatype.
I propose to add the existing enumeration [PaymentMethod](https://schema.org/PaymentMethod) as another datatype. This way, standardized payment options can be used while handling an LocalBusiness as an MTE with PointOfInterest.

### The requested schema does not exist

- Proposal: add [PaymentMethod](https://schema.org/PaymentMethod) as an expected datatype to [payment Accepted](https://schema.org/paymentAccepted) 

## Why is this topic important for a broader audience?
- to standardize payment options beyond text values

> Example:
> an PointOfInterst MTE with LocalBusiness can have the payment option: http://purl.org/goodrelations/v1#Cash instead of possible ambiguous values like: "cash", "bar", "Bargeld"

**Comment by sumutcan** [comment]
noted. are goodrelations enumerations enough for this?

**Comment by FabianBerner1** [comment]
Yes, should be

**Comment by sumutcan** [comment]
final domain specification published.
