### ISSUE TITLE
[RC] Accommodation/LodgingBusiness

### ISSUE THREAD

**Issue by eliaskaerle** [ODTA/ds#3]
This is the RC (Request for Comments) for the **Accommodation/LodgingBusiness** RDS. Please use the comments section below for discussions.

**RDS Abstract:**
Im Folgenden geht es nicht um eine neue Domain Specification sondern die Properties, die für den
Bereich „Accommodation“ bzw. “Lodging Business” benötigt werden. Es wurde also geprüft, welche
Properties für „Accommodation“ und “Lodging Business” zur Verfügung stehen. Zudem werden in der
Folge die Properties angeführt, die aus Sicht der Autoren noch fehlen und es werden die Properties
angeführt für die die „expected Types“ fehlen oder ergänzt werden müssen. Das jeweilige to do ist
nachfolgend angegeben.

Link to RC: https://github.com/ODTA/ds/blob/main/docs/rc/AccommodationDS-RC-RDS.pdf
Link to RC's DS representation:  [https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=457kFvJAj](https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=457kFvJAj)

**Comment by FallicoNRW** [comment]
2.1 accessibilityFeature - Are we planning to use Reisen für Alle?

**Comment by FallicoNRW** [comment]
2.2 addressDestination - We do distinguish between different types of regions: tourism marketing region (regional DMOs), destinations, administrative districts, and municipalities.

**Comment by FallicoNRW** [comment]
2.3 addressType - We currently only use Lodging business address, Administrator, and Owner's address. Others not necessary in this context.

**Comment by FallicoNRW** [comment]
2.8 accommodationCategory - some suggested categories (such as double room, single room, penthouse, suite etc.) are features to one of the under-categories. The only under-categories we would add from the list would be apartment, vacation home, and vacation apartment.

**Comment by FallicoNRW** [comment]
2.12 kindOfLodgingBusiness - aren't these just additional categories?

**Comment by FallicoNRW** [comment]
2.13, 2.14, 2.15 - all these should be part of a feature list, with features of the accommodation itself (Hausausstattung) and features of the rooms (Zimmerausstattung)

**Comment by FabianBerner1** [comment]
> 2.1 accessibilityFeature - Are we planning to use Reisen für Alle?

+1 for using Reisen für Alle
additionally I think that it would make sense to add accessibilityFeature to PointOfInterest as well

**Comment by sumutcan** [comment]
> 2.12 kindOfLodgingBusiness - aren't these just additional categories?

yes. that's also how they are modelled

**Comment by sumutcan** [comment]
> 

true, but such list is not yet completely provided. so we leave it flexible with locationfeaturespecification for now

**Comment by sumutcan** [comment]
> 2.13, 2.14, 2.15 - all these should be part of a feature list, with features of the accommodation itself (Hausausstattung) and features of the rooms (Zimmerausstattung)

true, but such list is not yet completely provided. so we leave it flexible with locationfeaturespecification for now

**Comment by sumutcan** [comment]
> 2.3 addressType - We currently only use Lodging business address, Administrator, and Owner's address. Others not necessary in this context.

thanks. I'll bring this up in the final feedback meeting and see what others say.

**Comment by sumutcan** [comment]
@FabianBerner1 @eliaskaerle @FallicoNRW here is another doodle for a final feedback round for the lodgingbusiness DS
https://doodle.com/meeting/participate/id/dNOY6o2e

and here is the current draft version: https://odta.sti2.org/?dsb-list=7Kk-V4zwE&dsb-ds=ey7WKfQpL

please fill until 23.01.2022 EoD.
