### ISSUE TITLE
[RC] PostalAddress

### ISSUE THREAD

**Issue by eliaskaerle** [ODTA/ds#6]
This is the RC (Request for Comments) for the PostalAddress RDS. Please use the comments section below for discussions.

Link to RC: https://github.com/ODTA/ds/blob/main/docs/rc/PostalAddressDS-RC-RDS.pdf
Link to RC's DS representation: [https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=UwNDemJG4](https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=UwNDemJG4)

**Comment by FabianBerner1** [comment]
I don't really understand if [areaserved](https://schema.org/areaServed) can be used for the geo information of an object e.g. an POI or LodgingBusines.

LodgingBusines uses a maximum of 3 Types of PostalAddresses (object address, administrator and owner address) so the geo Property of LodgingBusiness can't be used for all 3 addresses.

If the areaServed property isn't meant for these types of geo information, I propose to add a new property for this purpose called [geo](https://schema.org/geo).
