### ISSUE TITLE
[RC] TouristAttraction

### ISSUE THREAD

**Issue by eliaskaerle** [ODTA/ds#7]
This is the RC (Request for Comments) for the TouristAttraction RDS. Please use the comments section below for discussions.

RDS Abstract:
Die vorliegende Anfrage beruht auf einem bereits in andere Form eingereichten Vorschlag,
der in der Zusammenkunft der ODTA am 09.02.2022 besprochen wurden. Autoren dieses
Vorschlages waren Detlef Klinge (TTG) Susanne Bleibel (TMBW) und Christian Stühring
(NRW Tourismus).
In der Zusammenkunft der ODTA am 09.02.2022 wurde der Autor gebeten den damaligen
Vorschlag in dieser Form erneut einzureichen.
Da die Form dieses Antrages in Hinblick auf Klassen, Eigenschaften und Enumerationen
recht allgemein gehalten ist, erfolgt der Verweis auf das Vorgängerdokument. Diesem
können alle Erweiterungen der Klassen, Eigenschaften und Enumerationen entnommen
werden.

Link to RC: https://github.com/ODTA/ds/blob/main/docs/rc/TouristAttractionDS-RC-RDS.pdf
Link to RC's DS representation:
- LandmarksOrHistoricalBuildings: [https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=guaBlSkyH](https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=guaBlSkyH)
- CaveOrMine: [https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=Ti_PjxjAl](https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=Ti_PjxjAl)
- CongressCenter: [https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=Wfk11lXlr](https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=Wfk11lXlr)
- HealthResort: [https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=NZhbC_tHS](https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=NZhbC_tHS)
- NatureAttraction: [https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=I4hdRYk1B](https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=I4hdRYk1B)
- Sauna: [https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=cxxiy3Cvv](https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=cxxiy3Cvv)
- TechnicalTouristAttraction: [https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=PCD34n4UZ](https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=PCD34n4UZ)
- PublicSwimmingPool: [https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=ovzm_dJ-t](https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=ovzm_dJ-t)
- EventVeniue: [https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=DNaXQ6Aqe](https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=DNaXQ6Aqe)
- TouristAttraction: [https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=CabI68ZJN](https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=CabI68ZJN)
- TouristAttraction as MTE Place & LocalBusiness: [https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=Qb2vaHx80](https://odta.sti2.org/?dsb-list=nAnWVfvH3&dsb-ds=Qb2vaHx80)

**Comment by SunderlandNRW** [comment]
2.2. CaveOrMine - as main category not necessary, if there are only 3 under categories, of which 2 are included in the title. Maybe it should be called Underground or sth else?

**Comment by SunderlandNRW** [comment]
2.2. CaveOrMine - Number of Stairs necessary. Maybe Boolean better? Stairs yes or no.

**Comment by SunderlandNRW** [comment]
2.2. CaveOrMine - what is meant by minimale and maximale Meereshöhe?

**Comment by SunderlandNRW** [comment]
2.2. CaveOrMine - new properties accessModality, pathLength, pathCondition, numberOfLevels, numberOfStairs, undergroundTemperature, undergroundHumidity and undergroundDripActivity as new properties. The rest (and potentially more) can be represented with the additionalProperty property. - we agree, except for the necessity of undergroundDripActivity.

**Comment by SunderlandNRW** [comment]
2.3 Congress Center - isn't a Congress Centre a type of EventVenue (see 2.13)?

**Comment by SunderlandNRW** [comment]
2.4. Kureinrichtung/ Health Resort - Kureinrichtung maybe too close to rehabilitation and resort is defined as a large complex with a hotel and/or several other types of accommodation . Possibly the type could be called "Recreation and Health"?

Undercategory suggestions:
Spa/Sauna 
Health Resort/rehabilitation clinic
Kneipp pool/water treading
Wellness/cosmetics
Brine/ Salina (Gradierwerk)
Therapeutic bath/Healing spring
Retirement and nursing home

**Comment by SunderlandNRW** [comment]
2.4. HealthResort - suggested additional properties are very medical. Could be alright as additional information. But do we need to think more touristy? (see my other comment concerning to 2.4)

**Comment by SunderlandNRW** [comment]
2.5. NatureAttraction - Suggestion for Enumeration: 
Nature board/information point	
Park/ Nature Visitor centre	
Nature discovery track
Barbecue hut/barbecue area	
Pavilion Shelter/ hut
Mountain peak	
Game park/wildlife enclosure	
Nature reserve/natural monument	
Forest
Moor
Heathland
Lake	
Pond
Canal
Water spring

**Comment by SunderlandNRW** [comment]
2.6. Sauna - Extra type Sauna not necessary. Possibly the different types of Saunas/ Steam rooms etc. available could be included as features in 2.4. HealthResort bzw. Recreation and Health

**Comment by SunderlandNRW** [comment]
2.7. TechnicalTouristAttraction
Maybe property industrialCulture better? Are subcategories really necessary?

**Comment by SunderlandNRW** [comment]
2.8. TouristicSwimmingPool - PublicSwimmingPool type but no specific subtypes. To specify different types of swimming pools we propose a property called kindOfPOI with PublicSwimmingPoolEnumeration as range. -Agree. Suggestions: 
Adventure pool
Leisure pool
Thermal bath
Outdoor pool
Indoor swimming pool

**Comment by SunderlandNRW** [comment]
2.11. amenity feature - makes sense in general, however wouldn't it be possible to link a gastronomical data type with a TouristAttraction so that one won't need an amenity gastronomy?

**Comment by SunderlandNRW** [comment]
2.14. Subtypes for Parks not just the area is informative but also an enumeration of the "types" e.g. national park, natural parks?

**Comment by SunderlandNRW** [comment]
2.17. Zoo 
Wouldn't it be interesting to know how many animals/ what kind of animals there are?

**Comment by SunderlandNRW** [comment]
2.19. Parking facilities - what about including either a text box or a URL (connecting to data spaces like Parkopedia?) for external parking space information?

**Comment by SunderlandNRW** [comment]
"There are some minor questions left in the document as footnotes, however the major recommendation we would like to make is to split this RDS into multiple ones (ideally one per type) for further discussion, as in its current state it will be very complicated to focus the discussion on specific types and properties." I agree

**Comment by sumutcan** [comment]
> 2.11. amenity feature - makes sense in general, however wouldn't it be possible to link a gastronomical data type with a TouristAttraction so that one won't need an amenity gastronomy?

yes, this is also how I would do it. But I also understand that some POIs may just want to generally inform that food establishments are available, without annotating a specific one. we can discuss this in the feedback meeting.

**Comment by sumutcan** [comment]
> 2.2. CaveOrMine - what is meant by minimale and maximale Meereshöhe?

the lowest and highest point of the cave regarding the sea level. but this is anyway an additionalProperty value..

**Comment by sumutcan** [comment]
> 2.2. CaveOrMine - as main category not necessary, if there are only 3 under categories, of which 2 are included in the title. Maybe it should be called Underground or sth else?

not all caves are underground. I will leave it like this for now, we can discuss during the feedback round.

**Comment by sumutcan** [comment]
> 2.2. CaveOrMine - new properties . - we agree, except for the necessity of undergroundDripActivity.

will bring it up during the feedback round

**Comment by sumutcan** [comment]
> 2.3 Congress Center - isn't a Congress Centre a type of EventVenue (see 2.13)?

good catch. I will remove the new congress centre type and add it as an enuemration member to the EventVenueEnumeration

**Comment by sumutcan** [comment]
> 2.17. Zoo Wouldn't it be interesting to know how many animals/ what kind of animals there are?

maybe I'll bring it up during the feedback meeting

**Comment by sumutcan** [comment]
> 



> 2.19. Parking facilities - what about including either a text box or a URL (connecting to data spaces like Parkopedia?) for external parking space information?

the sameAs property can be used for this.
